<form method="post" id="<?php echo $this->formid ?>" action="<?php echo $this->url ?>">
    <div class="fieldsets-wrapper">
        <?php echo $this->token; ?>

        <?php if(sizeof($this->filter)): ?>
            <?php foreach($this->filter as $filter_key => $filter_options): ?>
                <fieldset class="grid-elements">
                    <legend><?php echo $filter_options['label']; ?></legend>
                    <select id="filter_<?php echo $filter_key; ?>" name="<?php echo $filter_key; ?>">
                        <option value="-1"></option>
                        <?php foreach($filter_options['values'] as $key => $value): ?>
                            <?php 
                                $selected = false; 
                                if(in_array($key, $_POST)){
                                    $selected = true;
                                }
                            ?>
                            <option <?php echo $selected ? 'selected="selected"' : ''; ?> value="<?php echo $key ?>"><?php echo $value ?></option>
                        <?php endforeach; ?>
                    </select> 
                    <button class="filter-button" type="submit" id="<?php echo "filter-{$filter_key}"; ?>">Filtruj</button>
                </fieldset>
            <?php endforeach; ?>
        <?php endif; ?>

        <fieldset class="grid-elements">
            <legend>Wyszukaj wg klienta</legend>
            <?php 
                $value = null;
                if(array_key_exists('client_filter', $_POST)){
                    $value = $_POST['client_filter'];
                }
            ?>
            <input type="text" name="client_filter" <?php echo is_null($value) ? "" : "value=\"{$value}\""; ?>></input>
            <button class="filter-button" type="submit"  id="search-button">Wyszukaj</button>
        </fieldset>

        <?php if(sizeof($this->export)): ?>
        <fieldset class="grid-elements">
            <legend>Eksportuj wybrane zamówienia</legend>
            <select id="export" name="export" class="span2">
                <option value="-1"></option>
                <?php foreach($this->export as $key => $value): ?>
                    <?php 
                        $selected = false; 
                        if(in_array($key, $_POST)){
                            $selected = true;
                        }
                    ?>
                    <option <?php echo $selected ? 'selected="selected"' : ''; ?> value="<?php echo $key ?>"><?php echo $value['label'] ?></option>
                <?php endforeach; ?>
            </select> 
            <button class="filter-button export-button" type="submit"  id="export-button">Eksportuj</button>
        </fieldset>
        <?php endif; ?>
        
        <div class="clearfix"></div>
    </div>
    <table cellspacing="0" cellpadding="10">
        <thead>
            <tr>
                <th></th>
                <?php 
                    $dir = (strtolower((string) $this->dir) == 'asc') ? 'desc' : 'asc';
                    ?>
                <th>Lp.</th>
                <?php 
                    $sortClass = ($this->sort == 'unique') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'unique') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'unique', 'dir' => $sortDir)); ?>">Nr zam</a></th>
                <?php 
                    $sortClass = ($this->sort == 'ebay_id') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'ebay_id') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'ebay_id', 'dir' => $sortDir)); ?>">Nr Ebay</a></th>
                <?php 
                    $sortClass = ($this->sort == 'invoice_id') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'invoice_id') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'invoice_id', 'dir' => $sortDir)); ?>">Nr FV</a></th>
                <?php 
                    $sortClass = ($this->sort == 'model') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'model') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'model', 'dir' => $sortDir)); ?>">Model</a></th>
                <?php 
                    $sortClass = ($this->sort == 'color') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'color') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'color', 'dir' => $sortDir)); ?>">Kolor</a></th>
                <?php 
                    $sortClass = ($this->sort == 'is_seat') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'is_seat') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'is_seat', 'dir' => $sortDir)); ?>">Fotelik</a></th>
                <?php 
                    $sortClass = ($this->sort == 'frame') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'frame') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'frame', 'dir' => $sortDir)); ?>">Stelaż</a></th>
                <?php 
                    $sortClass = ($this->sort == 'wheels') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'wheels') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'wheels', 'dir' => $sortDir)); ?>">Koła</a></th>
                <th class="text_left">Dodatki</th>
                <?php 
                    $sortClass = ($this->sort == 'client') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'client') ? $dir : "desc";
                ?>
                <th class="text_left"><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'client', 'dir' => $sortDir)); ?>">Klient</a></th>
                <?php 
                    $sortClass = ($this->sort == 'date_of_payment') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'date_of_payment') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'date_of_payment', 'dir' => $sortDir)); ?>">Data opłacenia</a></th>
                <?php 
                    $sortClass = ($this->sort == 'date_of_receipt') ? "class=\"sort-{$this->dir}\"" : "class=\"sort-desc\"";
                    $sortDir = ($this->sort == 'date_of_receipt') ? $dir : "desc";
                ?>
                <th><a <?php echo $sortClass; ?> href="<?php echo $this->urlQuery(array(), null, null, null, array('sort' => 'date_of_receipt', 'dir' => $sortDir)); ?>">Data odbioru</a></th>
            </tr>
        </thead>
        <tbody>
            <?php $first = true; ?>
            <?php foreach($this->paginator as $key => $order): ?>
                <?php
                    $days = $this->orderDaysLeft($order->date_of_payment);
                    $urgency = $this->orderUrgency($days);
                    $days_message = !is_null($days) ? "($days dni do końca)" : "";
                ?>
                <tr class="order-row <?php echo $first ? 'first' : ''; ?> <?php echo "urgency-{$urgency}"; ?>" id="<?php echo "order-{$order->id}"; ?>">
                    <?php $hasMassActionCheckBox = false; ?>
                    <?php if(sizeof($this->massactions) && $hasMassActionCheckBox === false): ?>
                        <td style="text-align:center;" class="checkbox-column">
                            <?php if(isset($order[$this->massactionfield])): ?>
                                <input type="checkbox" name="selected[]" value="<?php echo urlencode($order[$this->massactionfield]); ?>">
                                <?php $hasMassActionCheckBox = true; ?>
                            <?php endif; ?>  
                        </td>
                    <?php endif; ?>
                    <td class="order"><?php echo (1 + $key); ?></td>
                    <td class="unique"><?php echo $this->cellNullRenderer($order->unique); ?></td>
                    <td class="ebay_id"><?php echo $this->cellNullRenderer($order->ebay_id); ?></td>
                    <td class="invoice_id"><?php echo $this->cellNullRenderer($order->invoice_id); ?></td>
                    <td class="model"><?php echo $order->model; ?></td>
                    <td class="color"><?php echo $order->color; ?></td>
                    <td class="is_seat"><?php echo ($order->is_seat == 1) ? 'Tak' : 'Nie'; ?></td>
                    <td class="frame"><?php echo $order->frame; ?></td>
                    <td class="wheels"><?php echo $order->wheels; ?></td>
                    <td class="bonus text_left"><?php echo $order->bonus; ?></td>
                    <td class="client text_left"><?php echo $order->client; ?></td>
                    <td class="date_of_payment"><?php echo $this->cellNullRenderer($order->date_of_payment); ?><br /><span class="days-left"><?php echo $days_message; ?></span></td>
                    <td class="date_of_receipt"><?php echo $this->cellNullRenderer($order->date_of_receipt); ?></td>
                    <td class="action-column update">
                        <div>
                        <a class="column-action update" href="<?php echo $this->url(array(
                            'controller' => 'order',
                            'action' => 'update',
                            'order_id' => $order->id
                        ), 'order_update'); ?>">Edytuj</a>
                        <br />
                        <a class="column-action delete" href="<?php echo $this->url(array(
                            'controller' => 'order',
                            'action' => 'delete',
                            'order_id' => $order->id
                        ), 'order_delete'); ?>">Usuń</a>
                        </div>
                    </td>
                </tr>
                <?php $first = false; ?>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div id="pagination">
        <?php echo $this->paginationControl($this->paginator,
                'Sliding',
                'pagination.phtml',
                array('sort' => $this->sort, 'dir' => $this->dir)); ?>
    </div>
    <div id="legend">
        <h4>Legenda</h4>
        <p><span class="urgency-high"></span>&nbsp;&nbsp;pilne</p>
        <p><span class="urgency-medium"></span>&nbsp;&nbsp;średnio pilne</p>
    </div>
</form>