<?php /*
<style type="text/css">
    #export table td, 
    #export table th{
        text-align: center;
    }

    #export .order-row .date_of_payment{
        font-weight: bold;
    }
    #export .order-row .date_of_receipt{
        width: 10%;
    }

    #export .order-row .unique,
    #export .order-row .color,
    #export .order-row .model,
    #export .order-row .is_seat,
    #export .order-row .date_of_payment,
    #export .order-row .frame,
    #export .order-row .action-column,
    #export .order-row .wheels,
    #export .order-row .order{
        width: 3%;
    }

    #export td.empty-cell{
        color: red;
    }

    #export tr.urgency-high td{
        background-color: tomato;
    }
    #export tr.urgency-medium td{
        background-color: yellow;
    }
	 h2{
        font-weight: bold;
        font-size: 16px;
    }
    h3{
        font-weight: normal;
        font-size: 16px;
    }
    
    #export th{
        font-weight: normal;
        color: white;
        background-color: black;
        padding: 5px;
    }
    #export td{
        border: 1px solid black;
        padding: 5px;
    }
    #export{
		color: black;
        font-size: 16px;
        font-family: Tahoma, sans-serif;
    }
	#export table{
        font-family: Tahoma, sans-serif;
        border: 1px solid black;
        color: black;
        font-size: 16px;
    }
</style>
	*/?>
<div id="export">
    <h2>Wyeksportowane zamówienia</h2>
    <h3>data: <?php echo date('Y-m-d H:i:s'); ?>, ilość zamówień: <?php echo count($this->orders); ?></h3>
    <div id="view-content">
        <table cellspacing="0" cellpadding="10">
            <thead>
                <tr>
                    <th>Nr zam</th>
                    <th>Nr FV</a></th>
                    <th>Model</a></th>
                    <th>Kolor</th>
                    <th>Fotelik</th>
                    <th>Stelaż</th>
                    <th>Koła</th>
                    <th class="text_left">Dodatki</th>
                    <th class="text_left">Klient</th>
                    <th>Data opłacenia</th>
                    <th>Data odbioru</th>
                </tr>
            </thead>
            <tbody>
                <?php $first = true; ?>
                <?php foreach($this->orders as $key => $order): ?>
                    <?php
                        $days = $this->orderDaysLeft($order->date_of_payment);
                        $urgency = $this->orderUrgency($days);
                        $days_message = !is_null($days) ? "($days dni do końca)" : "";
                    ?>
                    <tr class="order-row <?php echo $first ? 'first' : ''; ?> <?php echo "urgency-{$urgency}"; ?>" id="<?php echo "order-{$order->id}"; ?>">
                        <td class="unique"><?php echo $this->cellNullRenderer($order->unique); ?></td>
                        <td class="invoice_id"><?php echo $this->cellNullRenderer($order->invoice_id); ?></td>
                        <td class="model"><?php echo $order->model; ?></td>
                        <td class="color"><?php echo $order->color; ?></td>
                        <td class="is_seat"><?php echo ($order->is_seat == 1) ? 'Tak' : 'Nie'; ?></td>
                        <td class="frame"><?php echo $order->frame; ?></td>
                        <td class="wheels"><?php echo $order->wheels; ?></td>
                        <td class="bonus text_left"><?php echo $order->bonus; ?></td>
                        <td class="client text_left"><?php echo $order->client; ?></td>
                        <td class="date_of_payment"><?php echo $this->cellNullRenderer($order->date_of_payment); ?><br /><span class="days-left"><?php echo $days_message; ?></span></td>
                        <td class="date_of_receipt"><?php echo $this->cellNullRenderer($order->date_of_receipt); ?></td>
                    </tr>
                    <?php $first = false; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>